# Base16 Tomorrow 256 - alacritty color config
# Chris Kempson (http://chriskempson.com)

# Default colors
[colors.primary]
background = '0xffffff'
foreground = '0x4d4d4c'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '0xffffff'
cursor = '0x4d4d4c'

# Normal colors
[colors.normal]
black = '0xffffff'
red = '0xc82829'
green = '0x718c00'
yellow = '0xeab700'
blue = '0x4271ae'
magenta = '0x8959a8'
cyan = '0x3e999f'
white = '0x4d4d4c'

# Bright colors
[colors.bright]
black = '0x8e908c'
red = '0xc82829'
green = '0x718c00'
yellow = '0xeab700'
blue = '0x4271ae'
magenta = '0x8959a8'
cyan = '0x3e999f'
white = '0x1d1f21'

[[colors.indexed_colors]]
index = 16
color = "0xf5871f"

[[colors.indexed_colors]]
index = 17
color = "0xa3685a"

[[colors.indexed_colors]]
index = 18
color = "0xe0e0e0"

[[colors.indexed_colors]]
index = 19
color = "0xd6d6d6"

[[colors.indexed_colors]]
index = 20
color = "0x969896"

[[colors.indexed_colors]]
index = 21
color = "0x282a2e"
