# Set prefix to Ctrl-a
set -g prefix C-a

# Set 256 colour terminal
set -g default-terminal "tmux-256color"

# Enable mouse
set -g mouse on

# Status bar
set -g status-left ""
set -g status-right "#[fg=#888888]Session: #[fg=#dddddd]#{session_name}"
set -g status-bg "#222222"
set -g window-status-format "#[fg=#888888]#{window_index}"
set -g window-status-current-format "#[fg=#dddddd]#{window_index}"

# Rebase numbering to start at 1
set -g base-index 1
set -g renumber-windows on
set -g automatic-rename on
